recordcatalog/urls.py
from django.urls import path
from . import views
from . import api
from .views import export_users_csv
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path("", views.index, name="index"),
    path("albums/", views.AlbumListView.as_view(), name="albums"),
    path("albums/<int:pk>", views.AlbumDetailView.as_view(), name="album-detail"),
    path("artists/", views.ArtistListView.as_view(), name="artists"),
    path("artists/<int:pk>", views.ArtistDetailView.as_view(), name="artist-detail"),
    path("genres/", views.GenreListView.as_view(), name="genres"),
    path("genres/<int:pk>", views.GenreDetailView.as_view(), name="genre-detail"),
    path("export", export_users_csv, name="export_users_csv"),
    path("wanted/", views.WantedListView.as_view(), name="wanted"),
    path("wanted/create/", views.WantedCreate.as_view(), name="wanted-create"),
    path("search_results/", views.search_results, name="search-results"),
    path("albumAPI", api.AlbumListAPIView.as_view(), name="api_albums"),
    path("artistAPI", api.ArtistListAPIView.as_view(), name="api_artists"),
    path("genreAPI", api.GenreListAPIView.as_view(), name="api_genres"),
    path("wantedAPI", api.WantedListAPIView.as_view(), name="api_wanted"),
    path("labelAPI", api.LabelListAPIView.as_view(), name="api_labels"),
    path("root", api.api_root),
]


urlpatterns += [
    path("artists/create/", views.ArtistCreate.as_view(), name="artist-create"),
    path(
        "artists/<int:pk>/update/", views.ArtistUpdate.as_view(), name="artist-update"
    ),
    path(
        "artists/<int:pk>/delete/", views.ArtistDelete.as_view(), name="artist-delete"
    ),
    path("albums/create/", views.AlbumCreate.as_view(), name="album-create"),
    path("albums/<int:pk>/update/", views.AlbumUpdate.as_view(), name="album-update"),
    path("albums/<int:pk>/delete/", views.AlbumDelete.as_view(), name="album-delete"),
]

recordcatalog/models.py
from django.db import models
from location_field.models.plain import PlainLocationField
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
import uuid
from sorl.thumbnail import ImageField
import requests
import re


class Place(models.Model):
    city = models.CharField(max_length=255)
    location = PlainLocationField(based_fields=["city"], zoom=4)

    class Meta:
        ordering = ["city"]

    def __str__(self):
        return self.city


class Genre(models.Model):
    name = models.CharField(
        max_length=200, help_text="Enter a musical genre (e.g. Folk)"
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("genre-detail", args=[str(self.id)])

    class Meta:
        ordering = ["name"]


class Label(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a label (e.g. Elektra)")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Album(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=200)
    artist = models.ForeignKey("Artist", on_delete=models.SET_NULL, null=True)
    release_date = models.IntegerField(null=True, blank=True)
    album_notes = models.TextField(blank=True, help_text="Notes about the album")
    internal_notes = models.TextField(blank=True, help_text="Internal notes")
    album_image = models.ImageField(blank=True, upload_to="images")
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this album")
    label = models.ManyToManyField(Label, help_text="Select a label for this album")
    album_format = models.CharField(
        max_length=200, help_text="Enter a format, such as CD, LP, or EP", blank=True
    )
    catalog_number = models.CharField("Catalog number", max_length=25, blank=True)

    CONDITION = (
        ("Excellent", "Excellent"),
        ("Good", "Good"),
        ("Poor", "Poor"),
        ("Unknown", "Unknown"),
    )

    condition = models.CharField(
        max_length=20,
        choices=CONDITION,
        blank=True,
        default="Unknown",
        help_text="Album condition",
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        return reverse("album-detail", args=[str(self.id)])

    def display_genre(self):
        return ", ".join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = "Genre"

    def display_label(self):
        return ", ".join(label.name for label in self.label.all()[:3])

    display_label.short_description = "Label"

    class Meta:
        permissions = (("internal", "Can view internal data"),)
        ordering = ["title"]

    def genres(self) -> list:
        return [a.name for a in self.genre.all()]

    def labels(self) -> list:
        return [a.name for a in self.label.all()]


class Artist(models.Model):
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100)
    discogs_id = models.CharField("Discogs ID", max_length=50, blank=True, null=True)
    artist_bio = models.TextField("Artist biography", blank=True, null=True)
    image_url = models.URLField(max_length=300, blank=True, null=True)
    date_active_start = models.IntegerField("Active", null=True, blank=True)
    date_active_end = models.IntegerField("Retired", null=True, blank=True)
    location = models.ForeignKey(
        "Place", on_delete=models.SET_NULL, null=True, blank=True
    )

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        return reverse("artist-detail", args=[str(self.id)])

    def __str__(self):
        if self.first_name:
            return f"{self.last_name}, {self.first_name}"
        else:
            return f"{self.last_name}"

    def bio(self):
        if not self.artist_bio:
            if self.discogs_id:
                CLEANR = re.compile("(\[a=)(.*?)(\])")
                r = requests.get(
                    f"https://api.discogs.com/artists/{self.discogs_id}"
                ).json()
                if "profile" in r:
                    profile = r["profile"]
                    profile = re.sub(CLEANR, r"\2", profile)
                    self.artist_bio = profile
                else:
                    profile = "No profile information available."
                self.save(update_fields=["artist_bio"])
                return profile


class Wanted(models.Model):
    title = models.CharField(blank=True, max_length=240)
    artist = models.CharField(blank=True, max_length=240)
    album_notes = models.TextField(blank=True, help_text="For extra info")

    def __str__(self):
        return self.title

recordcatalog/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from recordcatalog.models import Album, Artist, Genre, Label, Wanted
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .filters import AlbumFilter, ArtistFilter, GenreFilter
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import random
from django.http import HttpResponse
import csv
from datetime import datetime, timedelta
from django.db.models import CharField, Value as V, Count, Q
from django.db.models.functions import Cast, Coalesce, Concat


def index(request):
    num_albums = Album.objects.all().count()
    num_genres = Genre.objects.all().count()
    num_labels = Label.objects.all().count()
    num_artists = Artist.objects.count()

    context = {
        "num_albums": num_albums,
        "num_artists": num_artists,
        "num_genres": num_genres,
    }
    return render(request, "index.html", context=context)


class AlbumListView(generic.ListView):
    model = Album
    paginate_by = 20
    template_name = "recordcatalog/album_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = AlbumFilter(self.request.GET, queryset=self.get_queryset())
        return context


class AlbumDetailView(generic.DetailView):
    model = Album


class GenreDetailView(generic.DetailView):
    model = Genre


class GenreListView(generic.ListView):
    model = Genre
    paginate_by = 20
    template_name = "recordcatalog/genre_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = GenreFilter(self.request.GET, queryset=self.get_queryset())
        return context


class ArtistListView(generic.ListView):
    model = Artist
    paginate_by = 20
    template_name = "recordcatalog/artist_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = ArtistFilter(self.request.GET, queryset=self.get_queryset())
        return context


class ArtistDetailView(generic.DetailView):
    model = Artist


class ArtistCreate(PermissionRequiredMixin, CreateView):
    permission_required = "recordcatalog.internal"
    model = Artist
    fields = ["first_name", "last_name", "date_active_start", "date_active_end"]


class ArtistUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = "recordcatalog.internal"
    model = Artist
    fields = "__all__"


class ArtistDelete(PermissionRequiredMixin, DeleteView):
    permission_required = "recordcatalog.internal"
    model = Artist
    success_url = reverse_lazy("artists")


class AlbumCreate(PermissionRequiredMixin, CreateView):
    permission_required = "recordcatalog.internal"
    model = Album
    fields = "__all__"


class AlbumUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = "recordcatalog.internal"
    model = Album
    fields = "__all__"


class AlbumDelete(PermissionRequiredMixin, DeleteView):
    permission_required = "recordcatalog.internal"
    model = Album
    success_url = reverse_lazy("albums")


def export_users_csv(request):
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = 'attachment; filename="albums.csv"'
    writer = csv.writer(response)
    writer.writerow(
        [
            "title",
            "release_date",
            "album_format",
            "image",
            "catalog_number",
            "genre",
            "label",
            "condition",
            "album_notes",
            "internal_notes",
            "artist",
            "artist_location",
            "artist_active_start",
            "artist_active_end",
            "created_at",
        ]
    )
    qs = Album.objects.prefetch_related("genre", "label")
    for album in qs:
        writer.writerow(
            [
                album.title,
                album.release_date,
                album.album_format,
                album.album_image,
                album.catalog_number,
                "|".join(c.name for c in album.genre.all()),
                "|".join(c.name for c in album.label.all()),
                album.condition,
                album.album_notes,
                album.internal_notes,
                album.artist,
                album.artist.location,
                album.artist.date_active_start,
                album.artist.date_active_end,
                album.created_at,
            ]
        )

    return response
    success_url = reverse_lazy("")


class WantedListView(generic.ListView):
    model = Wanted
    template_name = "recordcatalog/wanted_list.html"


class WantedCreate(PermissionRequiredMixin, CreateView):
    permission_required = "recordcatalog.internal"
    model = Wanted
    fields = "__all__"
    success_url = reverse_lazy("wanted")


def search_results(request):
    if request.method == "POST":
        search_query = request.POST.get("search_query")
        albums = Album.objects.filter(title__icontains=search_query)
        artists = Artist.objects.filter(
            Q(last_name__icontains=search_query) | Q(first_name__icontains=search_query)
        )
        genres = Genre.objects.filter(name__icontains=search_query)
        return render(
            request,
            "recordcatalog/search_results.html",
            {
                "search_query": search_query,
                "albums": albums,
                "artists": artists,
                "genres": genres,
            },
        )
    else:
        return render(request, "recordcatalog/search_results.html", {})

recordcatalog/templates/recordcatalog/album_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Album</h1>

<p>Are you sure you want to delete the album: {{ album }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

recordcatalog/templates/recordcatalog/album_detail.html
{% extends "base_generic.html" %}

<div class="container-fluid">  

{% block content %}

<!--BREADCRUMB-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'albums' %}">Albums</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ album.title }}</li>
  </ol>
</nav>

<!--DETAIL DIV-->
<div class="container-fluid">
  <div class="detail-wrapper">
    <div class="detail-div">
      {% if album.album_image %}
      <a href="{{ album.get_absolute_url }}"><img src="{{album.album_image.url}}" alt="Album Image"></a>
      {% else %} 
      <a href="{{ album.get_absolute_url }}"><img src="https://www.ncenet.com/wp-content/uploads/2020/04/No-image-found.jpg" alt="Album Image"></a>
      {% endif %}      
    </div>
    <div class="detail-div">
      <ul class="no-bullets">
        <h1>{{ album.title }}</h1>
        <h2><a href="{{ album.artist.get_absolute_url }}">{{ album.artist }}</a></h2>
        <li><b>Genre:</b> {{ album.genre.all|join:", " }}</li>
        <li><b>Release:</b> {{album.release_date }}</li>
        <li><b>Format:</b> {{album.album_format}}</li>
        <li><b>Condition:</b> {{album.condition}}</li>
        <li><b>Label:</b> {{album.display_label}}</li>
        <br>
        {% if album.album_notes%}
        <li><em>{{ album.album_notes}}</em></li>
        {% endif %}
        {% if perms.recordcatalog.internal %}
        {% if album.internal_notes%}
        <li><em>{{ album.internal_notes | safe | linebreaks }}</em></li>
        {% endif %}
        {% endif %}    
        <li> {% if perms.recordcatalog.internal %}
        <a class="btn btn-outline-dark" href="{% url 'album-update' album.id %}" role="button">Update album details</a>
  <a class="btn btn-outline-dark" href="{% url 'album-delete' album.id %}" role="button">Delete album</a>
  {% endif %}</li>
      </ul>
       
    </div>
  </div>
</div>

</div>
{% endblock %}

recordcatalog/templates/recordcatalog/album_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

recordcatalog/templates/recordcatalog/album_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}

<div class="container-fluid">  




{% block content %}

<!--BREADCRUMB-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Albums</li>
  </ol>
</nav>

<!--FILTER-->
<form method="GET" >
  <!-- <div class="form-group"> -->
    <div class="form-group col-sm-5 col-md-4">
    {{ filter.form|bootstrap }}
    <button type="submit" class="btn btn-dark btn-sm">Search</button>
  </div>
</form> 



<div class="list-grid">
{% for album in filter.qs %}
  <div class="list-grid-item">
    {% if album.album_image %}
    <a href="{{ album.get_absolute_url }}"><img src="{{album.album_image.url}}" alt="Album Image"></a>
    {% else %} 
    <a href="{{ album.get_absolute_url }}"><img src="https://www.ncenet.com/wp-content/uploads/2020/04/No-image-found.jpg" alt="Album Image"></a>
    {% endif %}  
    <br>
    <a href="{{ album.get_absolute_url }}">{{album.title}}</a>
    <br>
    <p class="grid-item-para">{% if album.artist.first_name %}{{album.artist.first_name}}{% endif %}{% if album.artist.first_name %} {% endif %}{% if album.artist.last_name %}{{album.artist.last_name}}{% endif %}</p>
  </div>

{% endfor %}
</div>
{% endblock %}

</div>

recordcatalog/templates/recordcatalog/artist_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Artist</h1>

<p>Are you sure you want to delete the artist: {{ artist }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

recordcatalog/templates/recordcatalog/artist_detail.html
{% extends "base_generic.html" %}
<div class="container-fluid">

{% block content %}




<!--BREADCRUMB-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'artists' %}">Artists</a></li>
    <li class="breadcrumb-item active" aria-current="page">{% if artist.first_name %}{{artist.first_name}}{% endif %}{% if artist.first_name %} {% endif %}{% if artist.last_name %}{{artist.last_name}}{% endif %}</li>
  </ol>
</nav>

         

<!--DETAIL DIV-->
<div class="container-fluid">
  <div class="detail-wrapper">
    <div class="detail-div">
    {% if artist.image_url %}
      <a href="{{artist.get_absolute_url}}"><img src="{{artist.image_url}}" alt="Artist Image"></a>
       {% else %} 
       <a href="{{artist.get_absolute_url}}"><img src="https://www.ncenet.com/wp-content/uploads/2020/04/No-image-found.jpg" alt="Artist Image"></a>
    {% endif %}

    </div>
    <div class="detail-div">
      <ul class="no-bullets">
        <h1>{% if artist.first_name %}{{artist.first_name}}{% endif %}{% if artist.first_name %} {% endif %}{% if artist.last_name %}{{artist.last_name}}{% endif %}</h1>
        <li>{% if artist.date_active_start %}{{artist.date_active_start}}{% endif %}{% if artist.date_active_start %}-{% endif %}{% if artist.date_active_end %}{{artist.date_active_end}}{% endif %}</li>
        <li>{% if artist.location %}{{artist.location}}{{artist.place}}{% endif %}</li>
        <li>{% if artist.artist_bio %}{{artist.artist_bio | linebreaks}}{% else %}{{artist.bio | linebreaks }}{% endif %}</li>
        
        <li><a href="https://www.discogs.com/artist/{{artist.discogs_id}}" class="btn btn-outline-dark">Search for {% if artist.first_name %}{{artist.first_name}}{% endif %}{% if artist.first_name %} {% endif %}{% if artist.last_name %}{{artist.last_name}}{% endif %} in Discogs</a>{% if perms.recordcatalog.internal %}
        <a class="btn btn-outline-dark" href="{% url 'artist-update' artist.id %}" role="button">Update artist details</a>
        <a class="btn btn-outline-dark" href="{% url 'artist-delete' artist.id %}">Delete artist</a></li>
        {% endif %}
      </ul>
      {% if artist.album_set.all %}
      <table class="table table-bordered">

        <thead class="table-active"> 
            <tr>
              <th scope="col">Albums</th>
              <th scope="col">Release</th>
            </tr>
          </thead>

          <tbody>
          {% for album in artist.album_set.all %}
              <tr>
                <td><a href="{% url 'album-detail' album.pk %}">{{album}}</a></td>
                <td>{{album.release_date}}</td>
              </tr>
          {% endfor %}
          </tbody>
      </table>
      {% endif %}


    </div>
  
    </div>

    </div>
 
  </div>
</div>

</div>
{% endblock %}

recordcatalog/templates/recordcatalog/artist_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

recordcatalog/templates/recordcatalog/artist_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}


<div class="container-fluid">  





{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Artists</li>
  </ol>
</nav>

<!--FILTER-->
<form method="GET">
  <div class="form-group col-sm-5 col-md-4">
    {{ filter.form|bootstrap }}
    <button type="submit" class="btn btn-dark btn-sm">Search
    </button>
  </div>
</form>



<!--BODY-->
<div class="list-grid">
{% for artist in filter.qs %}
  <div class="list-grid-item">
    {% if artist.image_url %}
      <a href="{{artist.get_absolute_url}}"><img src="{{artist.image_url}}" alt="Artist Image"></a>
       {% else %} 
       <a href="{{artist.get_absolute_url}}"><img src="https://www.ncenet.com/wp-content/uploads/2020/04/No-image-found.jpg" alt="Artist Image"></a>
    {% endif %}      
      <a href="{{ artist.get_absolute_url }}">
      {% if artist.first_name %}{{artist.first_name}}{% endif %}{% if artist.first_name %} {% endif %}{% if artist.last_name %}{{artist.last_name}}{% endif %}
      </a>
  </div>
  {% endfor %}
</div>
{% endblock %}


</div>

recordcatalog/templates/recordcatalog/genre_detail.html
{% extends "base_generic.html" %}

<div class="container-fluid">
{% block content %}

<!--BREADCRUMB-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'genres' %}">Genres</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ genre.name }}</li>
  </ol>
</nav>

<br>
<h1 class="text-left display-5">{{genre.name}}</h1>
<br>
<hr class="mt-0 mb-4">

 <!--TABLE GENRE DETAIL-->
<div class="table-responsive">
{% if genre.album_set.all %}
<table class="table table-striped table-bordered">
  <thead class="table-dark"> 
    <tr>
      <th scope="col">Album title</th>
      <th scope="col">Artist</th>
    </tr>
  </thead>

<tbody>
{% for album in genre.album_set.all %}
    <tr>
      <td><a href="{% url 'album-detail' album.pk %}">{{album}}</a></td>
      <td>{{album.artist}}</td>
    </tr>
{% endfor %}
</tbody>
</table>
{% else %}
<p>There are no albums of this genre.</p>
{% endif %} 
</div>
{% endblock %}
</div>
</div>

recordcatalog/templates/recordcatalog/genre_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}


<div class="container-fluid">  


{% block content %}

<!--BREADCRUMB-->
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Genres</li>
  </ol>
</nav>



<div class="genre-list-grid">
{% if genre_list %}
{% for genre in filter.qs %}
<a href="{{ genre.get_absolute_url }}">{{genre.name}}</a>
{% endfor %}
{% else %}
<p>There are no genres in the library.</p>
{% endif %} 
</div>
{% endblock %}
  

</div>

recordcatalog/templates/recordcatalog/latest_records.html
{% for album in recent_records %}
<div class="card" style="width: 20rem;">
 {% if album.album_image %}
  <a href="{{album.get_absolute_url}}"><img class="card-img-top mx-auto" src="{{ album.album_image.url }}" alt="latest_album"></a>
 {% else %}
   <a href="{{album.get_absolute_url}}"><img class="card-img-top mx-auto" src="https://www.ncenet.com/wp-content/uploads/2020/04/No-image-found.jpg" alt="latest_album"></a>
 {% endif %}
  <div class="card-body" style="text-align:center">
  <h3><a href="{{ album.get_absolute_url }}">{{ album.title }}</a></h3>
  </div>
     <div class="card-footer" style="text-align:center">
      <small class="text-muted">Added {{ album.created_at }}</small>
    </div>
</div>
{% endfor %}

recordcatalog/templates/recordcatalog/search_results.html
{% extends "base_generic.html" %}
<div class="container-fluid">  

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Search Results</li>
  </ol>
</nav>


<div class="container-fluid"><br>
<h1 class="text-left display-5">Search Results</h1>
<br>
{% if search_query %}
<p>Showing search results for <span class="font-italic">"{{ search_query }}"</span></p>
<br>
<br>


{% if albums %}
<h3>Albums</h3>
<hr class="mt-0 mb-4">
{% for album in albums %}
<a href="{{ album.get_absolute_url }}">
{{ album }} - {{ album.artist }}
</a>
<br>
<br>
{% endfor %}
{% endif %}


{% if artists %}
<h3>Artists</h3>
<hr class="mt-0 mb-4">
{% for artist in artists %}
<a href="{{ artist.get_absolute_url }}">
{{ artist }}
</a>
<br>
<br>
{% endfor %}
{% endif %}



{% if genres %}
<h3>Genres</h3>
<hr class="mt-0 mb-4">
{% for genre in genres %}
<a href="{{ genre.get_absolute_url }}">
{{ genre }}
</a>
<br>
<br>
{% endfor %}
{% endif %}


{% else %}
<p>You did not search for anything.</p>
{% endif %}
</div>
{% endblock %}

recordcatalog/templates/recordcatalog/wanted_form.html
{% extends "base_generic.html" %}

{% block content %}
<div class="form-group">
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
</div>
{% endblock %}

recordcatalog/templates/recordcatalog/wanted_list.html
{% extends "base_generic.html" %}
{% load bootstrap %}
<div class="container-fluid">  

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Wanted</li>
  </ol>
</nav>


<div class="container-fluid"><br>
<h1 class="text-left display-5">Records to Buy</h1>
<br>
<hr class="mt-0 mb-4">
  


<!--TABLE WANTED LIST-->
<div class="table-responsive">
<table class="table table-striped table-bordered">
  <thead class="table-dark"> 
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Artist</th>
      <th scope="col">Notes</th>
    </tr>
  </thead>
  <tbody>

{% for wanted in wanted_list %}

    <tr>
      <td>{{ wanted.title }}</td>
      <td>{{wanted.artist}}</td>
      <td>{{wanted.album_notes}}</td>

    </tr>
{% endfor %}
</tbody>
</table>
</div>

<div class="container" style="margin-left:30px;margin-top:20px">  
<p><a href="{% url 'wanted-create' %}">Add wanted records</a></p>
</div>


{% endblock %}